name: Automatic Branch Merge

on:
  push:
    branches:
      - cicd

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge branches
        run: |
          git config user.name "naresh"
          git config user.email "smjnareshpatel@gmail.com"
          git fetch origin
          git checkout main
          #git merge --allow-unrelated-histories cicd
          git merge --no-ff ${{ github.sha }} -m "Merge branch 'cicd' into 'main'"
          git push origin main

          


