name: Automatic Branch Merge

on:
  push:
    branches:
      - cicd

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge branches
        run: |
          git config user.name "naresh"
          git config user.email "smjnareshpatel@gmail.com"
          echo "line 20"
          git fetch origin
          git checkout main
          echo "line 22"
          git config pull.rebase false  # merge
          git config pull.rebase true   # rebase
          git rebase --continue
          git rebase --skip
          git pull origin cicd --allow-unrelated-histories
          echo "line 24"
          git merge --no-ff ${{ github.sha }} -m "Merge branch 'cicd' into 'main'"
          echo "line 26"
          git push origin main
          echo "line 28"
          git add .
          git commit -m "check error"

          


